name: TickUHC
author: Ingenio
main: me.juan.uhc.Main
version: 1.0
load: POSTWORLD
website: https://twitter.com/Ingeniosin
description: If you have any questions you can contact @Ingeniosin.
depend:
  - WorldBorder

commands:
  freeze:
  practice:
  uhc:
  whitelist:


